services:
  db:
    image: postgres:15-alpine
    container_name: foodaware_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  python-service:
    build:
      context: ./python-service
    container_name: foodaware_python
    ports:
      - "8000:8000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: foodaware_backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PYTHON_SERVICE_URL=${PYTHON_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db
      - python-service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: foodaware_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
