name: CI Seguridad (GitLeaks)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ejecutar escaner de credenciales
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
